" =================
" vimrc --- vim Entry file
" Author: MuCheng
" License: GPLv3
" =================
"
if has('nvim')
  let g:_main = '/../.config_file/vim/config/main.vim'
else
  let g:_main = '/.config_file/vim/config/main.vim'
endif
execute 'source' fnamemodify(expand('<sfile>'), ':h').g:_main
  

