brew cask install iterm2
brew cask install java
brew cask install shadowsockesx
brew cask install firefox
brew cask install google-chrome
brew cask install docker
brew cask install vmware-fusion
brew cask install cheatsheet
brew cask install launchrocket
brew cask install reggy
brew cask install insomnia
