brew install mycli
brew install wget
brew install git
brew install tig
brew install tmate
brew install redis
brew install nmap
brew install sqlmap
brew install cloc
brew install ctop
brew install lnav
brew install gibo
