#!/usr/bin/env bash

install_path=$(
  cd $(dirname $0)
  pwd
)

config_path=$(
  cd $install_path/..
  pwd
)

echo "====> Config file root path is: ${config_path}"

if [[ `uname` == 'Darwin'  ]]; then
  # 安装包管理器
  if ! command -v brew >/dev/null 2>&1; then
    echo "====> Command [brew] is not be installed, Please install first."
  else
    echo "====> Commnad [brew] is already installed"
  fi

  if ! command -v tmux >/dev/null 2>&1; then
    echo "====> Command [tmux] is not be installed. Start to install..."
    brew install tmux
  else
    echo "=====> Command [tmux] is already installed"
  fi
else
  echo "xxxx> Current operating system is not supported"
  exit 1
fi

# tpm
echo "====> Install tumx plugins manage plugin tpm"
if [ ! -d ~/.tmux/plugins/tpm ]; then
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    
    if [ $? -ne 0 ]; then
      rm -r ~/.tmux/plugins/tpm >/dev/null 2>&1
      echo "xxxx> Download tpm failed, install stop"
      exit 1
    else
      echo "====> Download tpm Succeed"
    fi
fi

# backup
echo "====> Backup dir path is: ${config_path}/bak"
if [ ! -d $config_path/bak ]; then
    mkdir -p $config_path/bak
fi

if [ -f ~/.tmux.conf ]; then
    echo "====> Tmux config file [tmux.conf] is exist, backup and delete it."
    mv ~/.tmux.conf $config_path/bak/tmux.conf.bak
    rm ~/.tmux.conf >/dev/null 2>&1
fi

# link file
echo "====> Create tmux.conf link"
ln -s $config_path/tmux/tmux.conf ~/.tmux.conf
