" =================
" vimrc --- vim entry file
" Author: MuCheng
" License: GPLv3
" =================
"
let g:_main = '/.licht-config/vi/vim/config/main.vim'
execute 'source' fnamemodify(expand('<sfile>'), ':h').g:_main
